### ISSUE TITLE
Ну а хуле ты думал?

### ISSUE THREAD

**Issue by bitwiresys** [thedenisnikulin/data-analysis-project#1]
Естественно сайт с миллиардным оборотом не будет иметь уязвимостей тем более предсказуемой логики. Если ты не заметил там всё построено на крипте(sha256).
Единственный вариант это забрутфорсить биткоин транзу чтобы сгенеть 2 ляма хешей и сверить позиции.
Второй вариант более бредовый но тоже имеет место, это написать анализ игр и ставок за определённый период и сделать логику ставок с винрейтом от 91%

**Comment by thedenisnikulin** [comment]
Хахаха, да, ты прав. Если честно, я не сильно вникал в особенности работы сайта, а скрипт был написано по фану за несколько часов ночью.  Энивей, спасибо за идеи :)
